version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/surfer
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-deepseek-r1:1.5b}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - surfer-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=surfer
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - surfer-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - surfer-network

  # Optional: Include Ollama service if you want to run it locally
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - surfer-network

volumes:
  postgres_data:
  redis_data:
  ollama_data:

networks:
  surfer-network:
    driver: bridge 